### PR TITLE
Removed footer margin closing #252

### LINKED ISSUE #252: Footer has margin bottom.
**Describe the bug**
The footer has a margin on the bottom

tempsnip

### PR DESCRIPTION
**Pull request by ClientCrash**
Closes #252

### CODE REVIEW

File: components/Footer.vue [hunk 1]
```diff
@@ -55,7 +55,6 @@ export default {
 @use "../assets/css/mixins/screenSize";
 
 .footer {
-  margin-bottom: 40px;
   position: sticky;
```
Comment (MarcelCoding) [inline components/Footer.vue:58]:
```suggestion
  padding-bottom: 40px;
  position: sticky;
```

**Review by MarcelCoding — CHANGES_REQUESTED** [review]

**Review by MarcelCoding — APPROVED** [review]

**Review by JannikEmmerich — APPROVED** [review]
