### PR TITLE
Fixed Blog index page ordering issue

### LINKED ISSUE #274: Blog page shows post from oldest to newest.
**Describe the bug**
it should be the other way around.

### PR DESCRIPTION
**Pull request by ClientCrash**
**Issue**
Closes #274

### CODE REVIEW

File: pages/blog/index.vue [hunk 1]
```diff
@@ -48,6 +48,7 @@ export default {
     const responseFallback = await responseFallbackF.json()
     const response = mergePostArraysByIdPreferred(responsePreferred, responseFallback)
     this.posts = response
+    this.posts = this.posts.reverse()
```
Comment (MarcelCoding) [inline pages/blog/index.vue:51]: don't reverse, just inverse the sort in line 34

**Review by MarcelCoding — CHANGES_REQUESTED** [review]

**Review by DevMimas — APPROVED** [review]

File: pages/blog/index.vue (hunk 1 above)
Comment (ClientCrash) [reply pages/blog/index.vue]: done

**Review by MarcelCoding — APPROVED** [review]
